<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   Copyright (C) 2005 - 2017 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');

// Create shortcuts to some parameters.
$params  				= $this->item->params;
$images  				= json_decode($this->item->images);
$urls    				= json_decode($this->item->urls);
$canEdit 				= $params->get('access-edit');
$user    				= JFactory::getUser();
$info    				= $params->get('info_block_position', 0);
$app            = JFactory::getApplication();
$templateparams	= $app->getTemplate(true)->params;
$logo_s         = $templateparams->get('logo-s');

// Check if associations are implemented. If they are, define the parameter.
$assocParam = (JLanguageAssociations::isEnabled() && $params->get('show_associations'));
?>
<div class="wrapper container" itemscope="" itemtype="http://schema.org/NewsArticle">
	<div class="row justify-content-center">
		<!-- meta -->
		<meta itemscope="" itemprop="mainEntityOfPage" itemtype="https://schema.org/WebPage" itemid="<?php echo $_SERVER['HTTP_REFERER'] ?>">

		<span itemprop="author" itemscope="" itemtype="https://schema.org/Person">
	    <meta itemprop="name" content="<?php echo JFactory::getApplication()->get('sitename') ?>">
	  </span>

	  <span itemprop="publisher" itemscope="" itemtype="https://schema.org/Organization">
	    <span itemprop="logo" itemscope="" itemtype="https://schema.org/ImageObject">
	      <meta itemprop="url" content="<?php echo JURI::base().$logo_s ?>">
	    </span>
	    <meta itemprop="name" content="<?php echo JFactory::getApplication()->get('sitename') ?>">
	  </span>

		<div class="col-12 col-sm-12 col-md-12 col-lg-8 article-view">
			<article>
				<?php if (isset($images->image_fulltext) && !empty($images->image_fulltext)) : ?>
					<?php echo JLayoutHelper::render('joomla.content.cover_image', array('image' => htmlspecialchars($images->image_fulltext), 'alt' => htmlspecialchars($images->image_fulltext_alt))); ?>
				<?php endif; ?>

				<?php if ($this->params->get('show_page_heading')) : ?>
					<?php echo JLayoutHelper::render('joomla.content.title.title_heading', $this->escape($this->params->get('page_heading'))); ?>
				<?php endif; ?>

				<?php if ($params->get('show_title')) : ?>
					<?php echo JLayoutHelper::render('joomla.content.title.title_page', $this->escape($this->item->title)); ?>
				<?php endif; ?>


				<?php if ($params->get('show_publish_date') OR $params->get('show_create_date') OR $params->get('show_author') OR $params->get('show_category')) : ?>
					<?php echo JLayoutHelper::render('joomla.content.info-block-top', array('item' => $this->item, 'params' => $params, 'position' => 'above')); ?>
				<?php endif; ?>
				<?php if ($params->get('show_print_icon') || $params->get('show_email_icon')) : ?>
					<?php echo JLayoutHelper::render('joomla.content.icons', array('params' => $params, 'item' => $this->item, 'print' => false)); ?>
				<?php endif; ?>

				<?php // Content is generated by content plugin event "onContentAfterTitle" ?>
				<?php echo $this->item->event->afterDisplayTitle; ?>

				<?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
				<?php echo $this->item->event->beforeDisplayContent; ?>

				<?php if (isset($urls) && ((!empty($urls->urls_position) && ($urls->urls_position == '0')) || ($params->get('urls_position') == '0' && empty($urls->urls_position))) || (empty($urls->urls_position) && (!$params->get('urls_position')))) : ?>
					<?php echo $this->loadTemplate('links'); ?>
				<?php endif; ?>
				<?php if ($params->get('access-view')) : ?>

					<?php if (!empty($this->item->pagination) && $this->item->pagination && !$this->item->paginationposition && !$this->item->paginationrelative) : ?>
						<?php echo $this->item->pagination; ?>
					<?php endif; ?>

					<?php if (isset ($this->item->toc)) : ?>
						<?php echo $this->item->toc; ?>
					<?php endif; ?>

					<!-- render module -->
					<?php $modules = JModuleHelper::getModules('article-top'); ?>
					<?php //$attribs['style'] = 'sidebar'; ?>
					<?php foreach ($modules AS $module ) : ?>
						<?php echo JModuleHelper::renderModule($module, $attribs); ?>
					<?php endforeach; ?>
					<!-- render module -->

					<div itemprop="articleBody" class="articleBody">
						<?php echo $this->item->text; ?>
					</div>

					<?php if ($params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
						<?php $this->item->tagLayout = new JLayoutFile('joomla.content.tags'); ?>
						<?php echo $this->item->tagLayout->render($this->item->tags->itemTags); ?>
					<?php endif; ?>

					<?php if (isset($urls) && ((!empty($urls->urls_position) && ($urls->urls_position == '1')) || ($params->get('urls_position') == '1'))) : ?>
					<?php echo $this->loadTemplate('links'); ?>
					<?php endif; ?>

					<?php // Optional teaser intro text for guests ?>
				<?php elseif ($params->get('show_noauth') == true && $user->get('guest')) : ?>
				<?php echo JHtml::_('content.prepare', $this->item->introtext); ?>
					<?php // Optional link to let them register to see the whole article. ?>
					<?php if ($params->get('show_readmore') && $this->item->fulltext != null) : ?>
					<?php $menu = JFactory::getApplication()->getMenu(); ?>
					<?php $active = $menu->getActive(); ?>
					<?php $itemId = $active->id; ?>
					<?php $link = new JUri(JRoute::_('index.php?option=com_users&view=login&Itemid=' . $itemId, false)); ?>
					<?php $link->setVar('return', base64_encode(ContentHelperRoute::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language))); ?>
					<p class="readmore">
						<a href="<?php echo $link; ?>" class="register">
						<?php $attribs = json_decode($this->item->attribs); ?>
						<?php
						if ($attribs->alternative_readmore == null) :
							echo JText::_('COM_CONTENT_REGISTER_TO_READ_MORE');
						elseif ($readmore = $attribs->alternative_readmore) :
							echo $readmore;
							if ($params->get('show_readmore_title', 0) != 0) :
								echo JHtml::_('string.truncate', $this->item->title, $params->get('readmore_limit'));
							endif;
						elseif ($params->get('show_readmore_title', 0) == 0) :
							echo JText::sprintf('COM_CONTENT_READ_MORE_TITLE');
						else :
							echo JText::_('COM_CONTENT_READ_MORE');
							echo JHtml::_('string.truncate', $this->item->title, $params->get('readmore_limit'));
						endif; ?>
						</a>
					</p>
					<?php endif; ?>
				<?php endif; ?>
				<?php // Content is generated by content plugin event "onContentAfterDisplay" ?>

				<!-- render module -->
				<?php $modules = JModuleHelper::getModules('article-bottom'); ?>
				<?php //$attribs['style'] = 'sidebar'; ?>
				<?php foreach ($modules AS $module ) : ?>
					<?php echo JModuleHelper::renderModule($module, $attribs); ?>
				<?php endforeach; ?>
				<!-- render module -->

				<?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
				<?php echo $this->item->event->afterDisplayContent; ?>

				<div class="clearfix"></div>

				<?php echo JLayoutHelper::render('joomla.content.info-block-bottom', array('item' => $this->item, 'params' => $params)); ?>

				<!-- pagination -->
				<?php if (!empty($this->item->pagination) && $this->item->pagination && $this->item->paginationposition && !$this->item->paginationrelative) : ?>
					<?php echo $this->item->pagination; ?>
				<?php endif; ?>
				<!-- pagination -->
			</article>
		</div>

		<?php $modules = JModuleHelper::getModules('article-aside'); ?>
		<?php $attribs['style'] = 'sidebar'; ?>
		<?php if($modules): ?>
			<div class="col-12 col-sm-12 col-md-12 col-lg-4 sidebar d-print-none">
				<aside class="row">
					<!-- render module -->
					<?php foreach ($modules AS $module ) : ?>
						<?php echo JModuleHelper::renderModule($module, $attribs); ?>
					<?php endforeach; ?>
					<!-- render module -->
				</aside>
			</div>
		<?php endif; ?>

	</div><!-- end .row -->
</div><!-- end .container -->
